export enum ErrorCodes {
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
    INVALID_ERROR_CODE = 'INVALID_ERROR_CODE',
    INVALID_TYPE = 'INVALID_TYPE',
    REQUIRED_PARAMETER_MISSING = 'REQUIRED_PARAMETER_MISSING',
    MODULE_NOT_READY = 'MODULE_NOT_READY',
    STORAGE_FILE_ERROR = 'STORAGE_FILE_ERROR',
    NO_CONNECTION_DATA = 'NO_CONNECTION_DATA',
    INVALID_TARGET_TYPE = 'INVALID_TARGET_TYPE',
    TARGET_IS_EMPTY = 'TARGET_IS_EMPTY',
    NO_DISCORD_CLIENT = 'NO_DISCORD_CLIENT',
    CONNECTION_ERROR = 'CONNECTION_ERROR',
    DATABASE_OPTIONS_MISMATCH = 'DATABASE_OPTIONS_MISMATCH',
    ACHIEVEMENT_NOT_FOUND = 'ACHIEVEMENT_NOT_FOUND'
}
